name: update-security-file

on:
  push:
    branches:
      - main
    paths:
      - SECURITY.md
  workflow_dispatch:

jobs:
  update_security-file:
    permissions:
      contents: write
      pull-requests: write
      pages: write
    uses: thoughtbot/templates/.github/workflows/dynamic-security.yaml@44c188e35e68fc99b6a1a9c63097a01c6972a472
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
